footprint: [[-0.24, -0.27], [-0.24, 0.27], [0.24, 0.27], [0.24, -0.27]]
footprint_padding: 0.01

robot_base_frame: base_link

resolution: 0.05

obstacle_range: 5.0
raytrace_range: 5.5

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    map_type: costmap
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan}

inflation:
    inflation_radius: 1.25
    cost_scaling_factor: 2.58

range_sensor_layer:
  clear_threshold:    0.2
  mark_threshold:     0.8
  clear_on_max_reading: true
  topics: ["/geko/range/wheelbackleft_modified",
           "/geko/range/wheelbackright_modified",
           "/geko/range/wheelfrontleft_modified",
           "/geko/range/wheelfrontright_modified"]